name: flutter_app3
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^5.0.0
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  image_picker: ^0.7.2+1
  moor_flutter: ^4.0.0-nullsafety
  sqlite3_flutter_libs: ^0.4.1
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.1.0
  build_runner:

flutter:
  uses-material-design: true

